# Generated by Django 5.1.6 on 2025-02-18 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_applicant_status_question_time_limit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicant',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterUniqueTogether(
            name='applicant',
            unique_together={('email', 'position')},
        ),
    ]
