# Generated by Django 5.1.6 on 2025-02-24 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0005_interview_applicant_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicantresponse',
            name='video_response',
            field=models.FileField(blank=True, null=True, upload_to='videos/'),
        ),
    ]
