# Generated by Django 5.1.6 on 2025-02-25 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0006_alter_applicantresponse_video_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interview',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-01-01"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='position',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default="2022-01-01"),
            preserve_default=False,
        ),
    ]
