# Generated by Django 5.1.6 on 2025-03-01 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0009_position_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
    ]
