# Generated by Django 5.1.6 on 2025-03-07 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0011_alter_interview_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='candidate_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='interview',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
