# Generated by Django 5.1.6 on 2025-03-08 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0012_interview_candidate_name_interview_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
